export default [
  ['ADVANCE', 'advance'],
  // ['BAN', ''],
  ['CHAT', 'chat'],
  ['CHAT_COMMAND', 'chatCommand'],
  ['FRIEND_JOIN', 'friendJoin'],
  ['GRAB_UPDATE', 'grabUpdate'],
  ['HISTORY_UPDATE', 'historyUpdate'],
  ['MOD_SKIP', 'modSkip'],
  // ['MUTE', ''],
  // ['ROLE', ''],
  ['SCORE_UPDATE', 'scoreUpdate'],
  ['USER_JOIN', 'userJoin'],
  ['USER_LEAVE', 'userLeave'],
  ['USER_SKIP', 'userSkip'],
  ['VOTE_UPDATED', 'voteUpdate'],
  ['WAIT_LIST_UPDATE', 'waitListUpdate'],
];
